CREATE TABLE IF NOT EXISTS STUDENT (
  ROLL_NO TEXT PRIMARY KEY,
  NAME TEXT NOT NULL,
  ADDRESS TEXT,
  PHONE TEXT,
  AGE INTEGER
);
INSERT INTO STUDENT(ROLL_NO,NAME,ADDRESS,PHONE,AGE)VALUES
('1','RAM','DELHI','******',18),
('2','JOHN','AGRA','******',20),
('3','SURESH','DELHI','******',20),
('4','GITA','AGRA','******',18),
('5','HARISH','DELHI','******',19);
SELECT * FROM STUDENT
SELECT * FROM STUDENT WHERE AGE=18 AND ADDRESS='AGRA'
SELECT * FROM STUDENT WHERE AGE=18 AND NAME='RAM'
SELECT MAX(AGE)
FROM STUDENT
SELECT MIN(AGE)
FROM STUDENT